EWPP- 1845
openeuropa/oe_contact_forms pull request #44
Opened 2022-01-10 15:13 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-01-11 16:07 UTC, brummbar requested changes

2022-01-11 16:07 UTC, brummbar commented on composer.json
> +            "phpro/grumphp": true
Since we are here, let's use a nice alphabetic order 😄

2022-01-18 16:40 UTC, brummbar approved these changes

2022-01-18 17:28 UTC, 22Alexandra approved these changes

2022-01-19 09:29 UTC, merged