OEL-1134: Honeypot module created and test provided.
openeuropa/oe_contact_forms pull request #45
Opened 2022-02-15 14:08 UTC by Maxfire

## OPENEUROPA-1134

### Description
Honeypot submodule for antispam added.
Tests updated accordingly.

2022-02-16 13:30 UTC, drishu requested changes
Also enabled oe_contact_forms_honeypot in the runner

2022-02-16 13:30 UTC, drishu commented on composer.json
> +            "dealerdirect/phpcodesniffer-composer-installer": true
remove this, we already have sniffs installed

2022-02-16 13:30 UTC, drishu commented on tests/src/FunctionalJavascript/MessageFormTest.php
> +    // Disable the time limit.
pls include also an explanation in the comment as to why we need this

2022-02-16 15:20 UTC, drishu submitted a review, later dismissed

2022-02-17 14:22 UTC, brummbar requested changes

2022-02-17 14:22 UTC, brummbar commented on modules/oe_contact_forms_honeypot/oe_contact_forms_honeypot.module
> +  }
We can use `hook_form_BASE_FORM_ID_alter()`.

2022-02-17 14:22 UTC, brummbar commented on runner.yml.dist
> +    - "./vendor/bin/drush en oe_contact_forms_honeypot -y"
This we don't need to add it, let's keep it disabled by default.

2022-02-17 14:22 UTC, brummbar commented on tests/src/FunctionalJavascript/MessageFormTest.php
> +    'oe_contact_forms_honeypot',
This test is for the base module functionality. We need to write another test to check that honeypot is added correctly.

2022-02-17 17:46 UTC, brummbar approved these changes

2022-02-18 17:47 UTC, brummbar approved these changes

2022-02-18 18:20 UTC, drishu approved these changes

2022-02-18 18:26 UTC, merged