EWPP-2701: Add new optional fields to corporate forms.
openeuropa/oe_contact_forms pull request #58
Opened 2022-10-14 14:13 UTC by yenyasinn

2022-10-21 14:25 UTC, nagyad requested changes

2022-10-21 14:25 UTC, nagyad commented on tests/src/FunctionalJavascript/CorporateContactFormTest.php
> +    // contact language field is active.
We should test that it is not available for non-corporate forms.

2022-10-21 14:25 UTC, nagyad commented on tests/src/FunctionalJavascript/CorporateContactFormTest.php
> +    // contact language field is active.
Also I don't see the case when we have Preferred checkbox saved the Alternative checkbox is not disabled on page load.

2022-10-21 14:25 UTC, nagyad commented on oe_contact_forms.module
> +  }
Why we do this in a validate, we are not validating anything here we are setting the value of a field based on another field.

2022-10-21 14:25 UTC, nagyad commented on oe_contact_forms.post_update.php
> +    ->setLabel(t('Alternative contact language'))
In the base_field_info you avoided the code duplication, here why not? They are the same field with different labels.

2022-10-21 14:25 UTC, nagyad commented on src/Plugin/ConceptSubset/ContactLanguages.php
> +    $languages = [
This should be tested against a fixture containing the languages it has to contain.

2022-10-21 14:25 UTC, nagyad commented on js/related_checkboxes.js
> +   * Sets state of "Alternative contact language" checkbox based on "Preferred contact language" state.
Let's provide a proper method annotation here. Look for examples in core or ewcms.

2022-10-24 14:38 UTC, nagyad submitted a review, later dismissed

2022-10-26 10:08 UTC, sergepavle approved these changes

2022-10-26 10:22 UTC, nagyad approved these changes

2022-10-26 10:36 UTC, merged