EWPP-2703: Refactoring of ContactMessageForm to make it easier to extend
openeuropa/oe_contact_forms pull request #61
Opened 2022-10-24 17:22 UTC by yenyasinn

2022-10-26 09:23 UTC, nagyad requested changes

2022-10-26 09:23 UTC, nagyad commented on src/Form/ContactMessageForm.php
> +  protected function setRedirectUrl(ContactFormInterface $contact_form, FormStateInterface $form_state) {
: void

2022-10-26 10:46 UTC, yenyasinn commented on src/Form/ContactMessageForm.php
> +  protected function setRedirectUrl(ContactFormInterface $contact_form, FormStateInterface $form_state) {
fixed

2022-10-26 14:12 UTC, sergepavle approved these changes

2022-10-27 06:45 UTC, brummbar requested changes
If we are trying to add better extensibility, the newly protected methods should have better parameters. Now they take the minimum set needed for our current scenario, but won't be of much value for other non-ewcms cases.
To check with @imanoleguskiza

2022-10-27 07:00 UTC, imanoleguskiza commented
Let's rename the PR to better state what it does: Reduce cyclomatic complexity of ContactMessageForm

2022-10-28 08:31 UTC, sergepavle approved these changes

2022-11-03 08:53 UTC, nagyad approved these changes

2022-11-03 08:55 UTC, merged