EWPP-4157: Add cron function to delete old contact messages.
openeuropa/oe_contact_forms pull request #91
Opened 2024-03-19 16:16 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-03-20 15:35 UTC, nagyad requested changes

2024-03-20 15:35 UTC, nagyad commented on src/Plugin/views/field/ContactMessageRemainingDays.php
> +  public function __construct(array $configuration, $plugin_id, $plugin_definition, ConfigFactoryInterface $config_factory) {
/**
   * {@inheritdoc}
   */

2024-03-20 15:35 UTC, nagyad commented on tests/src/Functional/RemainingDaysTest.php
> + * Tests the contact link field.
Needs to be fixed.

2024-03-20 15:35 UTC, nagyad commented on tests/src/Functional/RemainingDaysTest.php
> +  use BrowserHtmlDebugTrait;
This is not needed.

2024-03-20 15:35 UTC, nagyad commented on oe_contact_forms.module
> +  }
This code is not tested.

2024-03-20 15:35 UTC, nagyad commented on oe_contact_forms.module
> +  $form['#submit'][] = '_oe_contact_forms_contact_storage_settings_submit';
The form field is not tested.

2024-03-22 16:59 UTC, nagyad approved these changes

2024-03-25 07:24 UTC, 22Alexandra commented on src/Plugin/views/field/ContactMessageRemainingDays.php
> +    }
Do we need the `else` here?
```suggestion
    $remaining_days = $auto_delete_days - floor((time() - $created_date) / (60 * 60 * 24));
```

2024-03-25 07:24 UTC, 22Alexandra commented on src/Plugin/views/field/ContactMessageRemainingDays.php
> +    $remaining_days = (int) $remaining_days < 0 ? 0 : (int) $remaining_days;
```suggestion
    $remaining_days = max((int)$remaining_days, 0);
```

2024-04-11 14:34 UTC, upchuk approved these changes

2024-04-11 14:34 UTC, hernani approved these changes

2024-04-11 14:34 UTC, merged